import type { ExampleGuide } from '../types'
import { CaseUpper, Fingerprint, PanelsTopLeft, Route, Terminal, UsersRound } from '@lucide/vue'

export const requestMilestones = [
  { event: 'route_decided', label: '选择模型' },
  { event: 'account_ordered', label: '选择账号' },
  { event: 'execution_completed', label: '模型执行完成' },
  { event: 'billable_usage_emitted', label: '提交计量事件' },
  { event: 'request_observed', label: '收到请求终态' },
]

export const exampleGuides: ExampleGuide[] = [
  {
    id: 'text-transform',
    title: '转换成大写',
    summary: '插件先把英文转成大写，再交给本地模型原样返回，你可以直接对照处理前后的文字',
    icon: CaseUpper,
    group: 'interactive',
    action: 'uppercase',
    actionLabel: '转换文本',
    capabilities: ['middleware'],
    expected: '试试 Hello, plugin!，返回的文字应为 HELLO, PLUGIN!',
  },
  {
    id: 'request-pipeline',
    title: '追踪一次请求',
    summary: '请求 demo-auto，由插件选择实际模型和执行账号，随后流式返回原文并记录用量',
    icon: Route,
    group: 'interactive',
    action: 'request',
    actionLabel: '发送请求',
    capabilities: ['models', 'executor', 'model_router', 'scheduler', 'billing', 'request_lifecycle', 'usage', 'web_socket_observer'],
    expected: '运行后查看实际模型、执行账号和 Token 用量，Echo 模型只回显文字，不回答问题',
  },
  {
    id: 'plugin-api',
    title: '调用插件接口',
    summary: '页面把文字发送到插件的 Echo 接口，再显示返回值，不经过模型或账号',
    icon: PanelsTopLeft,
    group: 'interactive',
    action: 'echo',
    actionLabel: '发送文本',
    capabilities: ['management'],
    expected: '例如发送“你好，插件”，接口会返回同样的文字',
  },
  {
    id: 'demo-accounts',
    title: '演示账号',
    summary: '准备两个本地账号，随后在账号管理中体验插件提供的登录、额度、资料和请求画像',
    icon: UsersRound,
    group: 'integration',
    action: 'accounts',
    actionLabel: '准备演示账号',
    capabilities: ['authentication', 'account_management', 'quota', 'request_profile', 'maintenance'],
    expected: 'Alpha、Bravo 是本插件的固定测试身份，不含第三方凭据，也不访问外部服务',
    steps: [
      '点击“准备演示账号”，创建或复用 Alpha 和 Bravo',
      '打开主站“账号管理”，筛选 Demo 平台，查看两个账号',
      '查看账号资料、刷新额度，或在编辑中选择 standard / concise 请求画像',
      '账号登录通过主站新增账号入口体验，后台资料刷新由宿主维护任务触发',
    ],
  },
  {
    id: 'terminal-command',
    title: '终端命令',
    summary: '不打开管理页面，也可以从网关命令行调用插件，用 ping 确认命令接入',
    icon: Terminal,
    group: 'integration',
    action: 'external',
    actionLabel: '',
    capabilities: ['command_line'],
    expected: '终端输出 capability-workbench pong，退出码为 0',
    steps: [
      '从插件配置中复制实例 ID，替换下方占位符',
      '在网关运行目录执行命令，沿用该环境的配置和数据库连接',
      '直接查看终端输出，CLI 的独立进程不会把结果写进当前网页',
    ],
    command: 'codex-proxy-rs plugin <实例 ID> ping',
  },
  {
    id: 'custom-authentication',
    title: '自定义认证',
    summary: '用插件定义的请求头识别调用者，再映射到宿主已有的测试 Key',
    icon: Fingerprint,
    group: 'integration',
    action: 'external',
    actionLabel: '',
    capabilities: ['frontend_authentication'],
    expected: 'demo 身份得到模型响应，改成 wrong 后应被拒绝，不会替代后台登录',
    steps: [
      '仅在独立测试环境启用本插件的客户端认证',
      '把外部身份 capability-workbench-demo-user 映射到一个可用的测试 Key',
      '准备演示账号后，使用下方命令请求 demo-echo，将地址替换为网关地址',
    ],
    command: `curl <网关地址>/v1/responses \\\n  -H 'Authorization: CapabilityWorkbench demo' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"model":"demo-echo","input":"Hello, plugin!"}'`,
  },
]
